### ISSUE TITLE
Application Package Can Not Install

### ISSUE THREAD

**Issue by ozserhatt** [evereux/pycatia-tools#1]
My Error is :
_mysql.c(29): fatal error C1083: i‡erme dosyas\x8d a‡\x8dlam\x8dyor: 'mysql.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2

from flask import render_template
from flask import url_for

from application import app

with app.app_context():

    m_dict_part = {
        'title': 'Part Tools',
        'menu_items': [
            {
                'url': url_for('part_new'),
                'title': 'New Part'
            },
            {
                'url': url_for('part_points'),
                'title': 'Points'
            },
            {
                'url': url_for('part_bounding_box'),
                'title': 'Bounding Box'
            },
        ]
    }

    m_dict_product = {
        'title': 'Product Tools',
        'menu_items': [
            {
                'url': url_for('product_new'),
                'title': 'New Product'
            },
            {
                'url': url_for('product_reorder'),
                'title': 'Reorder Product Tree'
            },
            {
                'url': url_for('product_attributes'),
                'title': 'Edit Product Attributes'
            },
        ]
    }

    m_dict_drafting = {
        'title': 'Drafting Tools',
        'menu_items': [
            {
                'url': url_for('drafting_views'),
                'title': 'Views'
            },
            {
                'url': url_for('drafting_save_as'),
                'title': 'Save As'
            },
            {
                'url': url_for('drafting_insert_template'),
                'title': 'Insert Template'
            },
        ]
    }

def render_menu(option: str):

    m_dict = None

    if option == 'part':
        m_dict = m_dict_part
    if option == 'product':
        m_dict = m_dict_product
    if option == 'drafting':
        m_dict = m_dict_drafting

    return render_template('partials/menu.html', m_dict=m_dict)

**Comment by ozserhatt** [comment]
I solved my problem :) I am sorry, you can close the issue

**Comment by evereux** [comment]
You can close tickets yourself. 

What actually was your problem and how did you solve it? Maybe others can learn.

**Comment by ozserhatt** [comment]
I did the following steps so that the problem solved and life got sweet again.

First I installed MySQL Connector/C from [here](https://downloads.mysql.com/archives/c-c/)

Second (after installation finished) I copied " MySQL Connector C 6.1 " folder from " Program files/MySQL " into " Program files (x86)/MySQL "

Note : Maybe you need to download MySQL from internet to see your files a folder "MySQL" 
But you can try create a folder "MySQL" in Program Files yourself.

**Comment by evereux** [comment]
This application doesn't require any database  connections?

**Comment by evereux** [comment]
.
